services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    entrypoint: /app/server-entrypoint.sh
    ports:
      - "8000:8000"
      
  nginx:
    restart: always
    image: nginx:1.23-alpine
    volumes:
      - static:/static
    ports:
      - "80:80"

volumes:
  static: