# Generated by Django 5.1.2 on 2024-11-05 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_agua', models.FloatField()),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
